# Generated by Django 2.2.4 on 2019-08-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190830_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
