# Generated by Django 2.2.4 on 2019-08-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_image', models.ImageField(upload_to='images/')),
                ('edu_title', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
